import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const project=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const dist=path.join(project,'dist'),artifacts=path.join(project,'artifacts');
const health=JSON.parse(fs.readFileSync(path.join(dist,'health.json'),'utf8'));
const releases=JSON.parse(fs.readFileSync(path.join(dist,'api/releases.json'),'utf8'));
fs.mkdirSync(artifacts,{recursive:true});
const filename=`dsha-web-${health.version}-${health.buildId}.tar.gz`,target=path.join(artifacts,filename);
execFileSync('tar',['-czf',target,'--exclude=*.apk','-C',dist,'.'],{windowsHide:true});
const hash=createHash('sha256').update(fs.readFileSync(target)).digest('hex');
fs.writeFileSync(target+'.sha256',`${hash}  ${filename}\n`);
fs.writeFileSync(path.join(artifacts,'deployment-manifest.json'),JSON.stringify({domain:'dsha.cc',buildId:health.buildId,version:health.version,webArchive:{file:filename,bytes:fs.statSync(target).size,sha256:hash},apkFiles:releases.releases.map(r=>({localPath:path.join(dist,r.url),remoteRelativePath:r.url.slice(1),bytes:r.bytes,sha256:r.sha256})),verification:'Web archive and both APKs must be uploaded before validating checksums.sha256. No server deployment has been performed by this packaging script.'},null,2)+'\n');
console.log(`Prepared ${filename} (${fs.statSync(target).size} bytes), plus ${releases.releases.length} separate APKs.`);
